---
# eureka 注册地址
eurekaUrl: 'http://xxx.xxx.xxx.xxx:8761/eureka/apps/'


# 中台服务器列表
mtList:
  - xxx.xxx.xxx.xxx



# 前台服务器列表
ftList:
  - xxx.xxx.xxx.xxx




# consul 地址
consulUrl: 'xxx.xxx.xxx.xxx:8500'